version: '3.4'

services:
  datasafe_samba:
    image: dperson/samba
    environment:
      TZ: 'America/Los_Angeles'
    networks:
      - default
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /mnt/datasafe:/mount:z
    command: '-s "datasafe;/mount;yes;no" -w "WORKGROUP" -n'

networks:
  default:
